version: "3"

services:
  api:
    container_name: api
    ports:
      - 5000:5000
    build:
      context: ./apps/api
      dockerfile: Dockerfile

  web:
    container_name: web
    ports:
      - 3000:3000
    build:
      context: ./apps/web
      dockerfile: Dockerfile

volumes:
  mongodata:
