
name: Run E2E

on:
  push:
    branches:
      - turbo

jobs:
  e2e:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./lib/e2e
          config-file: config.ci.json